<?php if (!$input->isHidden()): ?>
    <div class="form-input" id="form_input_<?= $input->getId() ?>">        
        <?= $this->fetch(':form/form-error', ['error' => $input->getError()]) ?>
        <?= $input->fetch() ?>
        <?php if ($input->getDescription()): ?>
            <div class="form-description">
                <?= $input->getDescription() ?>
            </div>
        <?php endif ?>
    </div>
<?php else: ?>
    <?= $input->fetch() ?>
<?php endif ?>